sudo: required
language: bash
services:
- docker
before_install:
- docker build -t jinwuzhao/emacs-rust .
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
env:
  global:
  - secure: mLk2BOKJ/ZhQ3caVXOtMN/6BMCXOr4F1iYrqI3WYn3cdioXQ+MHXYPXr30/J9mY0wIaM636m4cXuDTmnASLeSnEtFKpxGIxN/+W35t0Bn6/zig1NOqpxVPKW5N8v9CXVvhUO+qZAdzd2ttpPd1MEgLUrchvYJgzWENQQLn32U7cT5u96zOklDEh+juX4yedfXCAOGsTbLFZ9eG2lVaqjBTDj0JTuyhzF8GnuSrZaUty7vXyU3uZNJzynlNCX/h8uGsWRq0nP3YiBJiycJgmsQgtMkDaAATHdcUgotTYwTnHjr4kc44GJqQFkxpAeCSlEYl+p8CRXae0YdFfDnKZVFCkPk8qrB/9OhSGC/HiLRwX+4aku+Tz8xaIrXdG8WCGeFrY3L7hfEqAKFACcchninwXTnLIXb/RcwCJrsnv7g4WxmUs6QFsUGPEH4zQH9yQTu594X7i4uYJzDgkWIPdL84M+kjvjOl+yItv7F4aOYOLSt88mtw4n2egGtMlIzOK3dPqTcndQ7PC4NeLybQ0AScon70JVZv5y+DvjmepmeYsDcqubvSn2KEh0H1+dKa5t3OC6RHB0pmoWtYQlL32bE27Vg0IkkxP1dYkiDBQWyf9e++OyQ5PebPxJtNmet2S9GBv8RNhPWXSn8r2wGNN4Fn5w1hRTBCrGnwyp9eUbjdU=
  - secure: gva/YDKXj8A2wdDc6eaYzivqI/eAZbJBbM5e0En+eld/WuH1foH8cNxt+vrpyWN2y/ODB18ZVLGzYRh4P0yup+1u9tCvTzD9sk0BGE5L2OKJM+XmG16BgBzdy2gdVDoQl063Jcw1CHAdxQ02NXDxk/5mYkyTOh+6T9QQszYIP66SUhrXyF4YlB4GoxM6UIo37VcsSbz4ZEBrtJc/ODrE3QgKrEntNaxIDBPTlW7jpJgQkM6N+KeLUPKp40nHnbrreV9ntBQgiyELuwY1QaAzQmFMjxLDf8VQoOnCOAPfpx1dNtmXw+0A5ixwEUBchf6Jjick0Mfi/nb1h3S5FUZMqDdowxiFG9/TMcRoN/qV+iT3hlN3J5qD3ynUb4J9OYoOxlvKSs84jqZnm4ATUzLks1pF2iSfB1zMffWQ2uBXQG1DGlw6uGiGMllMvMgaArd/WUPg8S1WcliqI1fWStfTf9ceE8q1JnoXEVRfxVk1/0BQmRfUOnoz05AGWjVBmuMhiciSt8thQK25EbKBlVbS3f6Tj7bMj/lTAcqU4e0WTT/EJgh3nMUlqavfcwCN6HYYd/SQAHmKv8oNvVe/37s49wLYI/6qMjI590EBdTDj2D/+DO3MW2SRH88Nv6RVjCJ4AKyR06tWladbTxrw6PDC/D4IzhNRqPb2yEwsUSw43ks=
