#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push jinwuzhao/emacs-rust
docker tag jinwuzhao/emacs-rust jinwuzhao/emacs-rust:$TRAVIS_TAG
docker push jinwuzhao/emacs-rust:$TRAVIS_TAG
docker logout
